# Generated by Django 4.2.7 on 2023-11-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='AKA',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='name',
        ),
    ]
